In [1]:
import torch

In [2]:
torch.__version__

'1.1.0'

In [3]:
import onmt

In [4]:
onmt.__version__

'1.0.0'

In [5]:
import torchtext

In [6]:
from collections import defaultdict, Counter

In [7]:
defaultdict?

In [8]:
def tmp(**kwargs):
    eos = kwargs.get("eos", "</s>")
    print(eos)

In [9]:
tmp(**{'eos': None})

None


In [10]:
!python preprocess.py -train_src data/src-train.txt -train_tgt data/tgt-train.txt -valid_src data/src-val.txt -valid_tgt data/tgt-val.txt -save_data data/demo

[2020-01-07 14:13:00,829 INFO] Extracting features...
[2020-01-07 14:13:00,832 INFO]  * number of source features: 0.
[2020-01-07 14:13:00,832 INFO]  * number of target features: 0.
[2020-01-07 14:13:00,832 INFO] Building `Fields` object...
[2020-01-07 14:13:00,832 INFO] Building & saving training data...
[2020-01-07 14:13:00,833 WARNING] Shards for corpus train already exist, won't be overwritten, pass the `-overwrite` option if you want to.
[2020-01-07 14:13:00,833 INFO] Building & saving validation data...
[2020-01-07 14:13:00,833 WARNING] Shards for corpus valid already exist, won't be overwritten, pass the `-overwrite` option if you want to.


In [11]:
val = torch.load("./data/demo.valid.0.pt")

In [12]:
val

In [13]:
val.src_vocabs

[]

In [14]:
vars(val).keys()

dict_keys(['sort_key', 'src_vocabs', 'examples', 'fields'])

In [15]:
val.fields

[]

In [16]:
val.sort_key

<function onmt.inputters.text_dataset.text_sort_key(ex)>

In [17]:
val.src_vocabs

[]

In [18]:
vars(val.examples[0]).keys()

dict_keys(['src', 'tgt', 'indices'])

In [19]:
val.examples[0]

### torchtext

In [20]:
from torchtext import data

In [39]:
def tokenize(s):
    return s.strip().split()

bos='<s>'
eos='</s>'
pad='<blank>'
feat = data.Field(
    init_token=bos, eos_token=eos,
    pad_token=pad, tokenize=tokenize,
    include_lengths=True)

pos = data.TabularDataset(
path='data/tmp.txt', format='csv',
fields=[('text', feat)])

bos=None
eos=None
pad='<blank>'
feat_2 = data.Field(
    init_token=bos, eos_token=eos,
    pad_token=pad, tokenize=tokenize,
    include_lengths=False)

pos_2 = data.TabularDataset(
path='data/tmp.txt', format='csv',
fields=[('text', feat_2)])

In [40]:
pos

In [41]:
vars(pos).keys()

dict_keys(['examples', 'fields'])

In [42]:
pos.fields

{'text': <torchtext.data.field.Field at 0x1d1abf3db70>}

In [43]:
vars(pos.examples[0])['text']

['You', 'must', 'not', 'touch', 'the', 'shoes', 'with', 'the', 'scissors']

In [44]:
feat.build_vocab(pos)

In [45]:
feat.vocab.stoi

defaultdict(<bound method Vocab._default_unk_index of <torchtext.vocab.Vocab object at 0x000001D1ABF3D278>>,
            {'<unk>': 0,
             '<blank>': 1,
             '<s>': 2,
             '</s>': 3,
             'the': 4,
             '.': 5,
             'The': 6,
             'of': 7,
             'a': 8,
             'is': 9,
             'This': 10,
             'are': 11,
             'not': 12,
             'to': 13,
             'you': 14,
             'that': 15,
             'in': 16,
             'car': 17,
             'for': 18,
             'game': 19,
             'get': 20,
             'it': 21,
             'just': 22,
             'means': 23,
             'same': 24,
             'For': 25,
             'If': 26,
             'In': 27,
             'It': 28,
             'On': 29,
             'Still': 30,
             'You': 31,
             'across': 32,
             'and': 33,
             'by': 34,
             'difficult': 35,
             'does': 36,
 

In [48]:
vars(pos_2).keys()

dict_keys(['examples', 'fields'])

In [46]:
feat_2.build_vocab(pos_2)

In [47]:
feat_2.vocab.stoi

defaultdict(<bound method Vocab._default_unk_index of <torchtext.vocab.Vocab object at 0x000001D1ABE27DA0>>,
            {'<unk>': 0,
             '<blank>': 1,
             'the': 2,
             '.': 3,
             'The': 4,
             'of': 5,
             'a': 6,
             'is': 7,
             'This': 8,
             'are': 9,
             'not': 10,
             'to': 11,
             'you': 12,
             'that': 13,
             'in': 14,
             'car': 15,
             'for': 16,
             'game': 17,
             'get': 18,
             'it': 19,
             'just': 20,
             'means': 21,
             'same': 22,
             'For': 23,
             'If': 24,
             'In': 25,
             'It': 26,
             'On': 27,
             'Still': 28,
             'You': 29,
             'across': 30,
             'and': 31,
             'by': 32,
             'difficult': 33,
             'does': 34,
             'driving': 35,
             'everythi

### onmt dataset && vocab

In [49]:
ds = torch.load('data/demo.valid.0.pt')

In [79]:
ds

In [80]:
ds.fields

[]

In [81]:
ds.src_vocabs

[]

In [83]:
len(ds.examples)

3000

In [84]:
ds.examples[0]

In [85]:
vars(ds.examples[0]).keys()

dict_keys(['src', 'tgt', 'indices'])

In [87]:
vars(ds.examples[0])['src']

[['Parliament',
  'Does',
  'Not',
  'Support',
  'Amendment',
  'Freeing',
  'Tymoshenko']]

In [51]:
vocab = torch.load('data/demo.vocab.pt')

In [78]:
vocab

{'src': <onmt.inputters.text_dataset.TextMultiField at 0x1d1ad1c80b8>,
 'tgt': <onmt.inputters.text_dataset.TextMultiField at 0x1d1ad851550>,
 'indices': <torchtext.data.field.Field at 0x1d1ae42b048>}

In [52]:
type(vocab)

dict

In [54]:
vocab.keys()

dict_keys(['src', 'tgt', 'indices'])

In [60]:
vars(vocab['src'])

{'preprocessing': None,
 'postprocessing': None,
 'is_target': False,
 'fields': [('src', <torchtext.data.field.Field at 0x1d1ad1c8518>)]}

In [70]:
tmp_src = vars(vocab['src'])['fields'][0][1];tmp_src

In [73]:
tmp_src.vocab.itos

['<unk>',
 '<blank>',
 'the',
 ',',
 '.',
 'of',
 'and',
 'to',
 'in',
 'a',
 'is',
 'that',
 'for',
 'on',
 'The',
 'with',
 'be',
 'are',
 'I',
 'this',
 'as',
 'we',
 'have',
 'it',
 'not',
 'you',
 'by',
 'will',
 'from',
 'which',
 'has',
 'at',
 'an',
 'or',
 '-',
 'can',
 'our',
 '"',
 'was',
 'all',
 'European',
 'We',
 'your',
 'also',
 '&apos;s',
 'This',
 '&quot;',
 'been',
 'In',
 'would',
 'more',
 'Mr',
 'its',
 'should',
 'their',
 'It',
 'but',
 'one',
 'about',
 'Commission',
 's',
 'there',
 'they',
 'new',
 'must',
 'do',
 'very',
 'like',
 'President',
 '?',
 'only',
 'time',
 'other',
 'these',
 '&apos;',
 'who',
 'were',
 'us',
 'Europe',
 'what',
 'my',
 'such',
 'need',
 '/',
 'up',
 'people',
 'out',
 'no',
 'report',
 'now',
 'if',
 'into',
 'so',
 'than',
 'Parliament',
 'States',
 'countries',
 'many',
 'Union',
 'first',
 'when',
 'EU',
 'important',
 'some',
 'use',
 'well',
 'support',
 'Member',
 'make',
 'Council',
 'most',
 '!',
 'any',
 'take',
 'his'

In [75]:
tmp_tgt = vars(vocab['tgt'])['fields'][0][1];tmp_tgt

In [76]:
tmp_tgt.vocab.itos

['<unk>',
 '<blank>',
 '<s>',
 '</s>',
 ',',
 '.',
 'die',
 'der',
 'und',
 'in',
 'zu',
 'von',
 'den',
 'ist',
 'für',
 'mit',
 'das',
 'auf',
 'eine',
 'Sie',
 'des',
 'nicht',
 'im',
 'werden',
 'Die',
 'dass',
 'ein',
 'wir',
 'dem',
 'sich',
 'es',
 'auch',
 'sind',
 '-',
 'an',
 'wird',
 'ich',
 'haben',
 'als',
 'um',
 'oder',
 'hat',
 '&quot;',
 'über',
 'einer',
 'Ich',
 'bei',
 'sie',
 'aus',
 'wie',
 'Das',
 'einen',
 'zur',
 'können',
 'Wir',
 'einem',
 '"',
 'uns',
 'nach',
 'zum',
 'nur',
 'kann',
 'Der',
 'diese',
 '!',
 'Es',
 'durch',
 'noch',
 'dieser',
 'vor',
 'so',
 'Herr',
 'sehr',
 'wurde',
 'Kommission',
 '?',
 'aber',
 'daß',
 'wenn',
 'müssen',
 'diesem',
 'am',
 'In',
 'mehr',
 'sein',
 'alle',
 'er',
 'möchte',
 'man',
 'war',
 'Präsident',
 '/',
 'gibt',
 'dieses',
 'eines',
 'Europäischen',
 'bis',
 'Union',
 'was',
 'vom',
 'hier',
 'ihre',
 'Hotel',
 'unter',
 'unsere',
 'muss',
 'sowie',
 'zwischen',
 'Bericht',
 'Ihnen',
 'keine',
 'Europa',
 'Ihre',


In [77]:
vocab

{'src': <onmt.inputters.text_dataset.TextMultiField at 0x1d1ad1c80b8>,
 'tgt': <onmt.inputters.text_dataset.TextMultiField at 0x1d1ad851550>,
 'indices': <torchtext.data.field.Field at 0x1d1ae42b048>}

### onmt batch

In [109]:
data.BucketIterator?

In [115]:
vocab['src'].base_field

In [139]:
vocab

{'src': <onmt.inputters.text_dataset.TextMultiField at 0x1d1ad1c80b8>,
 'tgt': <onmt.inputters.text_dataset.TextMultiField at 0x1d1ad851550>,
 'indices': <torchtext.data.field.Field at 0x1d1ae42b048>}

In [140]:
ds.fields = vocab

In [141]:
ds.fields

{'src': <onmt.inputters.text_dataset.TextMultiField at 0x1d1ad1c80b8>,
 'tgt': <onmt.inputters.text_dataset.TextMultiField at 0x1d1ad851550>,
 'indices': <torchtext.data.field.Field at 0x1d1ae42b048>}

In [142]:
src_iter = data.BucketIterator(
    dataset=ds, batch_size=4)

In [143]:
src_iter


In [145]:
tt = next(iter(src_iter)); tt


[torchtext.data.batch.Batch of size 4]
	[.src]:('[torch.LongTensor of size 62x4x1]', '[torch.LongTensor of size 4]')
	[.tgt]:[torch.LongTensor of size 68x4x1]
	[.indices]:[torch.LongTensor of size 4]

In [147]:
tt.tgt

tensor([[[    2],
         [    2],
         [    2],
         [    2]],

        [[  355],
         [  297],
         [  115],
         [   42]],

        [[   20],
         [    0],
         [   36],
         [   65]],

        [[17329],
         [   18],
         [  252],
         [   35]],

        [[ 5505],
         [  623],
         [    0],
         [  943]],

        [[  450],
         [  186],
         [    4],
         [    4]],

        [[   36],
         [ 2031],
         [ 2057],
         [ 1026]],

        [[  238],
         [    0],
         [  166],
         [  186]],

        [[    4],
         [   15],
         [    6],
         [ 6582]],

        [[   25],
         [   44],
         [ 5481],
         [    4]],

        [[   26],
         [    0],
         [   26],
         [   96]],

        [[    0],
         [    8],
         [    4],
         [   29]],

        [[  212],
         [10244],
         [    6],
         [    6]],

        [[   83],
         [    6],
  

In [ ]:
tt.src.

In [146]:
tt.src

(tensor([[[  726],
          [   14],
          [  326],
          [   46]],
 
         [[ 7072],
          [ 1892],
          [   18],
          [   55]],
 
         [[    3],
          [ 2123],
          [  192],
          [   27]],
 
         [[    2],
          [    8],
          [    5],
          [  113]],
 
         [[22267],
          [    9],
          [   23],
          [  783]],
 
         [[    3],
          [ 1557],
          [    3],
          [   33]],
 
         [[   18],
          [   11],
          [   23],
          [ 1060]],
 
         [[ 9083],
          [  122],
          [22994],
          [  123]],
 
         [[   11],
          [  143],
          [  203],
          [  191]],
 
         [[    9],
          [ 6728],
          [    5],
          [    2]],
 
         [[23887],
          [    9],
          [    2],
          [  219]],
 
         [[   64],
          [    0],
          [ 4775],
          [ 1823]],
 
         [[   22],
          [ 4951],
          [   

### torchtext batch

In [97]:
train_iter = data.BucketIterator(
    dataset=pos, batch_size=4)

In [98]:
tmp = next(iter(train_iter))

In [99]:
tmp


[torchtext.data.batch.Batch of size 4]
	[.text]:('[torch.LongTensor of size 15x4]', '[torch.LongTensor of size 4]')

In [100]:
tmp.text

(tensor([[  2,   2,   2,   2],
         [ 75,  76,   6,  79],
         [217,   3,  37,  40],
         [ 36,   1,  42,   3],
         [ 12,   1, 130,   1],
         [128,   1,   4,   1],
         [  4,   1, 131,   1],
         [ 19,   1,   7,   1],
         [146,   1,   4,   1],
         [165,   1, 177,   1],
         [  4,   1,  48,   1],
         [ 24,   1,   5,   1],
         [ 56,   1,   3,   1],
         [  5,   1,   1,   1],
         [  3,   1,   1,   1]]), tensor([15,  3, 13,  4]))

In [101]:
train_iter_2 = data.BucketIterator(
    dataset=pos_2, batch_size=4)

In [104]:
tmp_2 = next(iter(train_iter_2)); tmp_2


[torchtext.data.batch.Batch of size 4]
	[.text]:[torch.LongTensor of size 13x4]

In [105]:
tmp_2.text

tensor([[ 73,  74,   4,  77],
        [215,   1,  35,  38],
        [ 34,   1,  40,   1],
        [ 10,   1, 128,   1],
        [126,   1,   2,   1],
        [  2,   1, 129,   1],
        [ 17,   1,   5,   1],
        [144,   1,   2,   1],
        [163,   1, 175,   1],
        [  2,   1,  46,   1],
        [ 22,   1,   3,   1],
        [ 54,   1,   1,   1],
        [  3,   1,   1,   1]])

In [148]:
import random

In [149]:
import os

In [150]:
os.listdir('.')

['.gitignore',
 '.ipynb_checkpoints',
 '.travis.yml',
 'available_models',
 'build',
 'CHANGELOG.md',
 'config',
 'CONTRIBUTING.md',
 'data',
 'dist',
 'docs',
 'floyd.yml',
 'floyd_requirements.txt',
 'github_deploy_key_opennmt_opennmt_py.enc',
 'LICENSE.md',
 'onmt',
 'OpenNMT_py.egg-info',
 'preprocess.py',
 'README.md',
 'requirements.opt.txt',
 'server.py',
 'setup.py',
 'tools',
 'train.py',
 'translate.py',
 'Untitled.ipynb']

In [152]:
random.shuffle(range(3))

TypeError: 'range' object does not support item assignment

In [155]:
a = 1
assert a == 0, '？？'

AssertionError: ？？